### ISSUE TITLE
distrobox 增加源外依赖

### ISSUE THREAD

**Issue by RevySR** [deepin-community/distrobox#4]
https://github.com/deepin-community/distrobox/blob/e69ebaa6f395570aa43f60b38781f8f33b01e919/debian/control#L16

1. 不应该添加源外的依赖 这样源自洽性不能保证的

2. uos曾经在部分架构提供过 `docker-ce` 软件包 
    不能保证 `docker-ce` 一定是一个官方的社区版本

3. 这个行为属于变相开口子 需要使用docker-ce的时候
    可以提供一个软件包 docker-ce-provide-docker 在 provide 提供docker.io 依赖 docker-ce

**Comment by xzl01** [comment]
认同第一点，现在问题在于 debian维护的docker.io 是指向 <https://mobyproject.org/> 是一个docker的开源fork ，而我指的docker-ce是docker官方维护的源提供的版本，并不能完全等同。

**Comment by xzl01** [comment]
> 可以提供一个软件包 docker-ce-provide-docker 在 provide 提供docker.io 依赖 docker-ce

是否可以理解为，这个软件包依赖源外软件包docker-ce？

**Comment by RevySR** [comment]
> > 可以提供一个软件包 docker-ce-provide-docker 在 provide 提供docker.io 依赖 docker-ce
> 
> 是否可以理解为，这个软件包依赖源外软件包docker-ce？

所以需要单独开一个仓库 enable 仓库才有这个软件包

**Comment by xzl01** [comment]
> 所以需要单独开一个仓库 enable 仓库才有这个软件包

我没有研究过docker-ce的再分发的规定，但是看其他发行版都没有提供docker-ce 是否存在这方面的风险还未知

**Comment by RevySR** [comment]
指的不是重分发docker 而是这个provide 需要用户必须明确知道是用了非deepin的东西

**Comment by xzl01** [comment]
> 指的不是重分发docker 而是这个provide 需要用户必须明确知道是用了非deepin的东西

明白，但是如果单独提供一个仓库，是否会增大用户的操作成本。是否需要在产品层面进行更改：例如在控制中心添加选项？

**Comment by Zeno-sole** [comment]
> > 指的不是重分发docker 而是这个provide 需要用户必须明确知道是用了非deepin的东西
> 
> 明白，但是如果单独提供一个仓库，是否会增大用户的操作成本。是否需要在产品层面进行更改：例如在控制中心添加选项？

这不就增加开发成本了？

**Comment by xzl01** [comment]
https://www.debian.org/doc/debian-policy/ch-archive.html#the-contrib-archive-area

**Comment by RevySR** [comment]
https://github.com/deepin-community/distrobox/blob/dddfaf0dfb6e773c8368b8ebedb599e34ca4d21d/debian/control#L16

docker-ce已经移除
